services:
  db:
    image: postgres:16.4
    env_file:
      - ./backend/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh ./entrypoint.sh
    volumes:
      - ./backend:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - ./backend/.env.production
    depends_on:
      - db
    expose:
      - '8000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=https://kairos.gr/api/
    depends_on:
      - backend
    volumes:
      - ./frontend/build:/usr/share/nginx/html

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/code/static:ro
      - media_volume:/code/media:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
