# Generated by Django 5.1.2 on 2024-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsparameter',
            name='parameter_category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gfsparameter',
            name='short_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gfsparameter',
            name='number',
            field=models.IntegerField(),
        ),
    ]
