# Generated by Django 5.1.2 on 2024-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_engine', '0002_gfsparameter_parameter_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfsparameter',
            name='parameter_category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gfsparameter',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
