# Generated by Django 5.1.1 on 2024-09-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicPlanet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('radius', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Geographic Planet',
                'verbose_name_plural': 'Geographic Planets',
            },
        ),
    ]
