# Generated by Django 5.1.2 on 2024-10-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicplacetranslation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
