# Generated by Django 5.1.2 on 2024-10-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_geographicplacetranslation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicplacetranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
