# Generated by Django 5.1.1 on 2024-09-24 11:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_geographiccategory_geographicdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('admin_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='geography.geographicdivision')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='geography.geographiccategory')),
            ],
            options={
                'verbose_name': 'Geographic Place',
                'verbose_name_plural': 'Geographic Places',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeographicPlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='geography.geographicplace')),
            ],
            options={
                'verbose_name': 'Geographic Place Translation',
                'db_table': 'geography_geographicplace_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='geographicplace',
            index=models.Index(fields=['longitude', 'latitude'], name='geography_g_longitu_45f7ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geographicplacetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
