# Generated by Django 5.1.1 on 2024-09-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_geographicplace_geographicplacetranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('geographicdivision_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geography.geographicdivision')),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
            ],
            bases=('geography.geographicdivision',),
        ),
    ]
