# Generated by Django 5.1.2 on 2024-10-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_alter_geographicplacetranslation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicplacetranslation',
            name='slug',
        ),
        migrations.AddField(
            model_name='geographicplace',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
    ]
