# Generated by Django 5.1.2 on 2024-10-19 18:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_remove_geographicplacetranslation_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicdivision',
            name='geographic_data',
        ),
        migrations.AddField(
            model_name='geographicdivision',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='geographicdivision',
            index=models.Index(fields=['slug'], name='geography_g_slug_48eeac_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicdivision',
            index=models.Index(fields=['boundary'], name='geography_g_boundar_1b7a4b_idx'),
        ),
    ]
