# Generated by Django 5.1.2 on 2024-10-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_geographicplacetranslation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFSForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('utc_cycle_time', models.CharField(choices=[('00', '00'), ('06', '06'), ('12', '12'), ('18', '18')], max_length=2)),
                ('forecast_data', models.JSONField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.geographicplace')),
            ],
            options={
                'unique_together': {('place', 'date', 'hour', 'utc_cycle_time')},
            },
        ),
    ]
