# Generated by Django 5.1.2 on 2024-10-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_geographicplacetranslation_description'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gfsforecast',
            options={'ordering': ['date', 'hour', 'utc_cycle_time']},
        ),
        migrations.AlterField(
            model_name='gfsforecast',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfs_forecasts', to='geography.geographicplace'),
        ),
        migrations.AddIndex(
            model_name='gfsforecast',
            index=models.Index(fields=['date', 'hour'], name='weather_gfs_date_d387ca_idx'),
        ),
        migrations.AddIndex(
            model_name='gfsforecast',
            index=models.Index(fields=['place', 'date'], name='weather_gfs_place_i_d5448b_idx'),
        ),
        migrations.AddIndex(
            model_name='gfsforecast',
            index=models.Index(fields=['utc_cycle_time'], name='weather_gfs_utc_cyc_d54fd0_idx'),
        ),
    ]
