# Generated by Django 5.1.2 on 2024-10-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_gfsforecast_options_alter_gfsforecast_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsforecast',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gfsforecast',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
