# Generated by Django 5.1.2 on 2024-10-14 16:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_gfsforecast_latitude_gfsforecast_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfsforecast',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
